print('--------------------------------- Classroom Day 3 ---------------------------------')
# fruits = ["apple", "banana", "tomato"]
# print(fruits)
# print('========== Append ==========')
# fruits.append("orange")
# print(fruits)
# print('========== Insert ==========')
# fruits.insert(0, "kiwi")
# print(fruits)
# print('========== Remove ==========')
# fruits.remove("banana")
# print(fruits)
# print('========== Pop ==========')
# fruits.pop()
# print(fruits)
# print('========== Sort ==========')
# fruits.sort()
# print(fruits)
# print('========== Reverse ==========')
# fruits.reverse()
# print(fruits)
# print('======== List Slicing ========')
# print(fruits[1:3])
# print('========== Range ===========')
# l = [x*x for x in range(1, 8)]
# print(l)
# print('======== Tuple ========')
# t = (1,2,[3,5,6])
# print(t)
# print('========== Tuple Append ==========')
# t2 = list(t)
# t2.append(4)
# t = tuple(t2)
# print(t2)
# print(t)
# print('----------------------------- Hands-On Exercise -----------------------------')
# marks = []
# input_subjects = int(input("Enter number of subjects: "))
# print("Enter marks:")
# for i in range(input_subjects):
#     input_marks = int(input())
#     marks.append(input_marks)
# print("Marks: {}".format(marks))
# average = sum(marks)//len(marks)
# print("Average Marks:")
# print(average)
print('----------------------------- Homework -----------------------------')
# - Use list comprehension to square 5 numbers
l = [x*x for x in range(1, 6)]
print("List of first 5 squares:", l)
# - Store 5 cities and sort alphabetically
city = ["New York", "Los Angeles", "Chicago", "Pune", "Nagpur"]
city.sort()
print("Sorted cities:", city)
# - Convert list to tuple and try modifying it to observe immutability
city_tuple = tuple(city)
print("City tuple:", city_tuple)
city = list(city_tuple)
city.append("Mumbai")
